# Site settings
title: The Godfather Barbers
email: rodrigoballaminut@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thegodfatherbarbers.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown