# Site settings
title: The Godfather Barbers
email: info@thegodfatherbarbers.co.nz
description: > # this means to ignore newlines until "baseurl:"
  The kind of vibe, product and service that we offer here at The Godfather 
  Barber's is something that we've fine-tuned in just under two years 
  (est. 2013) and something which, until we set up shop, was missing in 
  the Wellington region.
url: "http://thegodfatherbarbers.co.nz/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown